package cn.com.epicc.app.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * PICCService service = new PICCService();
 * PICCServicePortType portType = service.getPICCServiceHttpSoap11Endpoint();
 * portType.getBDbeanByIP(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "PICCService", targetNamespace = "http://service.app.epicc.com.cn", wsdlLocation = "http://219.142.99.204:8301/piccws/services/PICCService?wsdl")
public class PICCService extends Service {

	private final static URL PICCSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(cn.com.epicc.app.service.PICCService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = cn.com.epicc.app.service.PICCService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://219.142.99.204:8301/piccws/services/PICCService?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://219.142.99.204:8301/piccws/services/PICCService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		PICCSERVICE_WSDL_LOCATION = url;
	}

	public PICCService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public PICCService() {
		super(PICCSERVICE_WSDL_LOCATION, new QName(
				"http://service.app.epicc.com.cn", "PICCService"));
	}

	/**
	 * 
	 * @return returns PICCServicePortType
	 */
	@WebEndpoint(name = "PICCServiceHttpSoap11Endpoint")
	public PICCServicePortType getPICCServiceHttpSoap11Endpoint() {
		return super.getPort(new QName("http://service.app.epicc.com.cn",
				"PICCServiceHttpSoap11Endpoint"), PICCServicePortType.class);
	}

	/**
	 * 
	 * @return returns PICCServicePortType
	 */
	@WebEndpoint(name = "PICCServiceHttpSoap12Endpoint")
	public PICCServicePortType getPICCServiceHttpSoap12Endpoint() {
		return super.getPort(new QName("http://service.app.epicc.com.cn",
				"PICCServiceHttpSoap12Endpoint"), PICCServicePortType.class);
	}

	/**
	 * 
	 * @return returns PICCServicePortType
	 */
	@WebEndpoint(name = "PICCServiceHttpEndpoint")
	public PICCServicePortType getPICCServiceHttpEndpoint() {
		return super.getPort(new QName("http://service.app.epicc.com.cn",
				"PICCServiceHttpEndpoint"), PICCServicePortType.class);
	}

}
