package cn.com.epicc.app.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PICCServicePortType", targetNamespace = "http://service.app.epicc.com.cn")
public interface PICCServicePortType {

	/**
	 * 
	 * @param args0
	 * @return returns java.lang.Object
	 */
	@WebMethod(action = "urn:getBDbeanByIP")
	@WebResult(targetNamespace = "http://service.app.epicc.com.cn")
	@RequestWrapper(localName = "getBDbeanByIP", targetNamespace = "http://service.app.epicc.com.cn", className = "cn.com.epicc.app.service.GetBDbeanByIP")
	@ResponseWrapper(localName = "getBDbeanByIPResponse", targetNamespace = "http://service.app.epicc.com.cn", className = "cn.com.epicc.app.service.GetBDbeanByIPResponse")
	public Object getBDbeanByIP(
			@WebParam(name = "args0", targetNamespace = "http://service.app.epicc.com.cn")
			String args0);

	/**
	 * 
	 * @param args0
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "urn:sendIDInfo")
	@WebResult(targetNamespace = "http://service.app.epicc.com.cn")
	@RequestWrapper(localName = "sendIDInfo", targetNamespace = "http://service.app.epicc.com.cn", className = "cn.com.epicc.app.service.SendIDInfo")
	@ResponseWrapper(localName = "sendIDInfoResponse", targetNamespace = "http://service.app.epicc.com.cn", className = "cn.com.epicc.app.service.SendIDInfoResponse")
	public String sendIDInfo(
			@WebParam(name = "args0", targetNamespace = "http://service.app.epicc.com.cn")
			String args0);

}
